### ISSUE TITLE
使用客户端如何代理本地localhost或127.0.0.1的请求

### ISSUE THREAD

**Issue by ywager** [nohosts/client#14]
本地有个localhost/127.0.0.1服务，在使用client的情况下，是否也可以通过nohost进行转发服务？

**Comment by ywager** [comment]
本地有个localhost/127.0.0.1服务，在使用client的情况下，是否也可以通过nohost进行转发服务？

**Comment by avwo** [comment]
https://github.com/avwo/whistle/issues/266
