### ISSUE TITLE
客户端打包后如何做日志排查

### ISSUE THREAD

**Issue by linliyuan** [nohosts/client#16]
这边对客户端进行了改动，打包后部分mac机（目前只有一台）出现闪退问题，想问一下有什么方案可以打日志之类的进行排查吗？有遇到过一样的问题吗？
问题机型：
  型号名称：        MacBook Air
  型号标识符：        MacBookAir10,1
  型号：        Z127000CFCH/A
  芯片：        Apple M1

执行现象：首次安装后打开正常，退出软件后再次打开，展示了一下设置代理，不到一秒闪退。需要下载再次安装才能正常展示。退出软件又会出现同样问题。

**Comment by avwo** [comment]
看下有没有这个文件 `~/.WhistleAppData/whistle.log`

**Comment by linliyuan** [comment]
> 看下有没有这个文件 `~/.WhistleAppData/whistle.log`

看到日志里只有这两个错误，引发闪退的可能是第一个错误（跟触发事件相符合）。奇怪的是插件代码没有执行跟wifi相关的命令才对。

![image](https://user-images.githubusercontent.com/37769385/230809646-7170bb71-f8c3-4a3f-81b3-f3d5040f633d.png)
