### ISSUE TITLE
优化代码

### ISSUE THREAD

**Issue by avwo** [nohosts/client#3]
1. 更新 electron 到最新版本
2. 删除掉项目到 `bin` 目录
3. 将 https://github.com/nohosts/client/blob/master/app/lib/index.js#L9 改成 `process.env.PFORK_EXEC_PATH = process.env.EXEC_PATH;`，无需再打包 node，直接用 electron 自带的 node
4. 打包后在 windows 和 mac 上验证下是否 ok

**Comment by letshare** [comment]
done
