### ISSUE TITLE
nohost打包成客户端点选择环境跳到空白页面（Not Found）是什么原因呢？

### ISSUE THREAD

**Issue by Chaya-cai** [nohosts/client#5]
![image](https://user-images.githubusercontent.com/28433071/100953663-fe4ac900-354d-11eb-9762-403b06b5cb35.png)
![image](https://user-images.githubusercontent.com/28433071/100953695-0acf2180-354e-11eb-8c1f-9ef8f4d375e5.png)

**Comment by WzFFzW** [comment]
可以看看这里
![image](https://user-images.githubusercontent.com/22398844/100955453-82eb1680-3551-11eb-8d91-1f78ed88c4ee.png)

**Comment by WzFFzW** [comment]
插件可以参照这个：[whistle.nohost-imweb](https://github.com/nohosts/whistle.nohost-imweb)

**Comment by Chaya-cai** [comment]
是按照插件开发步骤来的，开发的插件本地安装跑whistle能访问 但是打包到nohost中就是空白页面

**Comment by WzFFzW** [comment]
你点开设置，看看 plugin 这个tab有没有你的插件

**Comment by Chaya-cai** [comment]
设置也是跳到Not Found页面

**Comment by Chaya-cai** [comment]
请问你调通了吗？可否加你qq请教下

**Comment by WzFFzW** [comment]
可以的，397788323

**Comment by WzFFzW** [comment]
已联系解决。插件要在client/app下安装
