### ISSUE TITLE
打开客户端白屏 什么都不显示

### ISSUE THREAD

**Issue by zhangchenna** [nohosts/client#9]

**Comment by wisetwo** [comment]
+1 windows和mac均如此，好像一开始要访问网络，mac上访问的弹框一闪而过无法操作；

调试模式下：
![image](https://user-images.githubusercontent.com/2604068/137249018-a9a90d9e-3757-4e2d-a78f-d5e341b61f48.png)

**Comment by WzFFzW** [comment]
> _No description provided._

客户端是自己打包的还是下载的，麻烦提供一下更多的信息

**Comment by WzFFzW** [comment]
> +1 windows和mac均如此，好像一开始要访问网络，mac上访问的弹框一闪而过无法操作；
> 
> 调试模式下： ![image](https://user-images.githubusercontent.com/2604068/137249018-a9a90d9e-3757-4e2d-a78f-d5e341b61f48.png)

@wisetwo 是需要访问网络，设置代理，不知道你的问题是什么？可以仔细描述一下吗？

**Comment by kenzung** [comment]
同白屏，试试macos11及以上，就会出现

**Comment by WzFFzW** [comment]
fix

https://github.com/nohosts/client/commit/1a5b60d145750ada71695dcb85cd96226ab82e41
